### ISSUE TITLE
Delivering images on bower package

### ISSUE THREAD

**Issue by ingedmundo** [crowdint/style#8]
There's an issue about delivering our sprite(svg) as part of the bower package. Inside the package we are using relative routes to the svg file that works well inside the project (when compiling the scss to css), the problem comes when trying to integrate this 'statics' routes to the client application, basically because of the asset pipeline and the fact that [Vendor subdirectories are not included when compiling assets on Rails 4.0](https://github.com/rails/rails/issues/11759).

Although you can add those files to the config.assets.precompile you would have to do this for each file you need to be precompiled. Above that, the routines that cdnfy assets dont look into vendor/css files to do the switching of the precompile image.

We we thinking in upload our image assets (the sprite in this scenario) to a aws cdn bucket and then link the served css/sass files poiting to this cdnfied file, instead of serving the image itself.

What do you guys think?

**Comment by softr8** [comment]
Interesting, well, yes that'd work, you can have the the svg in a cdn. You just have to make sure that the grunt cdnify task doesn't replace the path of the svg.

**Comment by FerPerales** [comment]
_Although you can add those files to the config.assets.precompile you would have to do this for each file you need to be precompiled._

Don't really get this part. Do you mean I have to add each file? AFAIK, you can add a complete folder

**Comment by hecbuma** [comment]
yes each file or do some weird codez there, I recommend go with the imgs from a CDN.

**Comment by ingedmundo** [comment]
@softr8 it doesn't replace the path. we did some test about that with @hecbuma.

@FerPerales yes, you can add the entire folder, but that implies doing this on each client implementation. Besides if you are using the css version cdnify task wont replace this file and you will endup having bucket version of you files and links in your css to local files.
